### ISSUE TITLE
regarding your adguard docker-compose.yml

### ISSUE THREAD

**Issue by ovizii** [dbeley/docker-compose#2]
You are using these env variables:

    environment:
      - PUID=1000
      - PGID=1000

Those are specifically used within linuxserver's docker images and are not part of the [adguard home docker image](https://hub.docker.com/r/adguard/adguardhome) you are usign so they won't work. They will only confuse people.

**Comment by ovizii** [comment]
Also pelase note that the volumes you are usign are wrong. According to [adguard home wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Docker) they should be:

```
        volumes:
            - ./work:/opt/adguardhome/work
            - ./confdir:/opt/adguardhome/conf
```

**Comment by dbeley** [comment]
Hey, thanks for opening this issue, I updated the docker-compose file.

(I just noticed this specific file is quite well indexed by Google so I might as well have a working file :grimacing: )

Thanks again!

**Comment by ovizii** [comment]
You're welcome.
